spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Yerzhanuly Yerkebulan
  group: 2413-IS
  mail:
    from: 40251@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions